package com.wx.dev.entity;

import java.util.Date;

public class TblCorpinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.id
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.corpId
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private String corpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.corpSecret
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private String corpsecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.corpName
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private String corpname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.accessToken
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private String accesstoken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.createDate
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_corpinfo.updDate
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	private Date upddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.id
	 * @return  the value of tbl_corpinfo.id
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.id
	 * @param id  the value for tbl_corpinfo.id
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.corpId
	 * @return  the value of tbl_corpinfo.corpId
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public String getCorpid() {
		return corpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.corpId
	 * @param corpid  the value for tbl_corpinfo.corpId
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setCorpid(String corpid) {
		this.corpid = corpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.corpSecret
	 * @return  the value of tbl_corpinfo.corpSecret
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public String getCorpsecret() {
		return corpsecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.corpSecret
	 * @param corpsecret  the value for tbl_corpinfo.corpSecret
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setCorpsecret(String corpsecret) {
		this.corpsecret = corpsecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.corpName
	 * @return  the value of tbl_corpinfo.corpName
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public String getCorpname() {
		return corpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.corpName
	 * @param corpname  the value for tbl_corpinfo.corpName
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setCorpname(String corpname) {
		this.corpname = corpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.accessToken
	 * @return  the value of tbl_corpinfo.accessToken
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public String getAccesstoken() {
		return accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.accessToken
	 * @param accesstoken  the value for tbl_corpinfo.accessToken
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.createDate
	 * @return  the value of tbl_corpinfo.createDate
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.createDate
	 * @param createdate  the value for tbl_corpinfo.createDate
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_corpinfo.updDate
	 * @return  the value of tbl_corpinfo.updDate
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public Date getUpddate() {
		return upddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_corpinfo.updDate
	 * @param upddate  the value for tbl_corpinfo.updDate
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	public void setUpddate(Date upddate) {
		this.upddate = upddate;
	}
}