package com.wx.dev.entity;

import java.util.Date;

public class TblCustomuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.id
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.corpId
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String corpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.userid
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.name
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.department
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.position
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.mobile
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.gender
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.email
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.weixinid
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String weixinid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.avatar
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.status
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.extattr
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private String extattr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.createDate
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_customuser.updDate
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	private Date upddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.id
	 * @return  the value of tbl_customuser.id
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.id
	 * @param id  the value for tbl_customuser.id
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.corpId
	 * @return  the value of tbl_customuser.corpId
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getCorpid() {
		return corpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.corpId
	 * @param corpid  the value for tbl_customuser.corpId
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setCorpid(String corpid) {
		this.corpid = corpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.userid
	 * @return  the value of tbl_customuser.userid
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.userid
	 * @param userid  the value for tbl_customuser.userid
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.name
	 * @return  the value of tbl_customuser.name
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.name
	 * @param name  the value for tbl_customuser.name
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.department
	 * @return  the value of tbl_customuser.department
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.department
	 * @param department  the value for tbl_customuser.department
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.position
	 * @return  the value of tbl_customuser.position
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.position
	 * @param position  the value for tbl_customuser.position
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.mobile
	 * @return  the value of tbl_customuser.mobile
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.mobile
	 * @param mobile  the value for tbl_customuser.mobile
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.gender
	 * @return  the value of tbl_customuser.gender
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.gender
	 * @param gender  the value for tbl_customuser.gender
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.email
	 * @return  the value of tbl_customuser.email
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.email
	 * @param email  the value for tbl_customuser.email
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.weixinid
	 * @return  the value of tbl_customuser.weixinid
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getWeixinid() {
		return weixinid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.weixinid
	 * @param weixinid  the value for tbl_customuser.weixinid
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setWeixinid(String weixinid) {
		this.weixinid = weixinid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.avatar
	 * @return  the value of tbl_customuser.avatar
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.avatar
	 * @param avatar  the value for tbl_customuser.avatar
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.status
	 * @return  the value of tbl_customuser.status
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.status
	 * @param status  the value for tbl_customuser.status
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.extattr
	 * @return  the value of tbl_customuser.extattr
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public String getExtattr() {
		return extattr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.extattr
	 * @param extattr  the value for tbl_customuser.extattr
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setExtattr(String extattr) {
		this.extattr = extattr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.createDate
	 * @return  the value of tbl_customuser.createDate
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.createDate
	 * @param createdate  the value for tbl_customuser.createDate
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_customuser.updDate
	 * @return  the value of tbl_customuser.updDate
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public Date getUpddate() {
		return upddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_customuser.updDate
	 * @param upddate  the value for tbl_customuser.updDate
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	public void setUpddate(Date upddate) {
		this.upddate = upddate;
	}
}