package com.wx.dev.entity;

import java.util.Date;

public class TblDeptcsvdata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_deptcsvdata.id
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_deptcsvdata.cbu
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	private String cbu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_deptcsvdata.code
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_deptcsvdata.name
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_deptcsvdata.createDate
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_deptcsvdata.updDate
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	private Date upddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_deptcsvdata.id
	 * @return  the value of tbl_deptcsvdata.id
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_deptcsvdata.id
	 * @param id  the value for tbl_deptcsvdata.id
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_deptcsvdata.cbu
	 * @return  the value of tbl_deptcsvdata.cbu
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public String getCbu() {
		return cbu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_deptcsvdata.cbu
	 * @param cbu  the value for tbl_deptcsvdata.cbu
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public void setCbu(String cbu) {
		this.cbu = cbu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_deptcsvdata.code
	 * @return  the value of tbl_deptcsvdata.code
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_deptcsvdata.code
	 * @param code  the value for tbl_deptcsvdata.code
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_deptcsvdata.name
	 * @return  the value of tbl_deptcsvdata.name
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_deptcsvdata.name
	 * @param name  the value for tbl_deptcsvdata.name
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_deptcsvdata.createDate
	 * @return  the value of tbl_deptcsvdata.createDate
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_deptcsvdata.createDate
	 * @param createdate  the value for tbl_deptcsvdata.createDate
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_deptcsvdata.updDate
	 * @return  the value of tbl_deptcsvdata.updDate
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public Date getUpddate() {
		return upddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_deptcsvdata.updDate
	 * @param upddate  the value for tbl_deptcsvdata.updDate
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	public void setUpddate(Date upddate) {
		this.upddate = upddate;
	}
}