package com.wx.dev.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TblEmployeecsvdataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public TblEmployeecsvdataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPtcodeIsNull() {
            addCriterion("ptCode is null");
            return (Criteria) this;
        }

        public Criteria andPtcodeIsNotNull() {
            addCriterion("ptCode is not null");
            return (Criteria) this;
        }

        public Criteria andPtcodeEqualTo(String value) {
            addCriterion("ptCode =", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeNotEqualTo(String value) {
            addCriterion("ptCode <>", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeGreaterThan(String value) {
            addCriterion("ptCode >", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ptCode >=", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeLessThan(String value) {
            addCriterion("ptCode <", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeLessThanOrEqualTo(String value) {
            addCriterion("ptCode <=", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeLike(String value) {
            addCriterion("ptCode like", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeNotLike(String value) {
            addCriterion("ptCode not like", value, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeIn(List<String> values) {
            addCriterion("ptCode in", values, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeNotIn(List<String> values) {
            addCriterion("ptCode not in", values, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeBetween(String value1, String value2) {
            addCriterion("ptCode between", value1, value2, "ptcode");
            return (Criteria) this;
        }

        public Criteria andPtcodeNotBetween(String value1, String value2) {
            addCriterion("ptCode not between", value1, value2, "ptcode");
            return (Criteria) this;
        }

        public Criteria andServicestatusIsNull() {
            addCriterion("serviceStatus is null");
            return (Criteria) this;
        }

        public Criteria andServicestatusIsNotNull() {
            addCriterion("serviceStatus is not null");
            return (Criteria) this;
        }

        public Criteria andServicestatusEqualTo(Integer value) {
            addCriterion("serviceStatus =", value, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusNotEqualTo(Integer value) {
            addCriterion("serviceStatus <>", value, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusGreaterThan(Integer value) {
            addCriterion("serviceStatus >", value, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("serviceStatus >=", value, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusLessThan(Integer value) {
            addCriterion("serviceStatus <", value, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusLessThanOrEqualTo(Integer value) {
            addCriterion("serviceStatus <=", value, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusIn(List<Integer> values) {
            addCriterion("serviceStatus in", values, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusNotIn(List<Integer> values) {
            addCriterion("serviceStatus not in", values, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusBetween(Integer value1, Integer value2) {
            addCriterion("serviceStatus between", value1, value2, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andServicestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("serviceStatus not between", value1, value2, "servicestatus");
            return (Criteria) this;
        }

        public Criteria andOldcodeIsNull() {
            addCriterion("oldCode is null");
            return (Criteria) this;
        }

        public Criteria andOldcodeIsNotNull() {
            addCriterion("oldCode is not null");
            return (Criteria) this;
        }

        public Criteria andOldcodeEqualTo(String value) {
            addCriterion("oldCode =", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeNotEqualTo(String value) {
            addCriterion("oldCode <>", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeGreaterThan(String value) {
            addCriterion("oldCode >", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeGreaterThanOrEqualTo(String value) {
            addCriterion("oldCode >=", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeLessThan(String value) {
            addCriterion("oldCode <", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeLessThanOrEqualTo(String value) {
            addCriterion("oldCode <=", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeLike(String value) {
            addCriterion("oldCode like", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeNotLike(String value) {
            addCriterion("oldCode not like", value, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeIn(List<String> values) {
            addCriterion("oldCode in", values, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeNotIn(List<String> values) {
            addCriterion("oldCode not in", values, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeBetween(String value1, String value2) {
            addCriterion("oldCode between", value1, value2, "oldcode");
            return (Criteria) this;
        }

        public Criteria andOldcodeNotBetween(String value1, String value2) {
            addCriterion("oldCode not between", value1, value2, "oldcode");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUpddateIsNull() {
            addCriterion("updDate is null");
            return (Criteria) this;
        }

        public Criteria andUpddateIsNotNull() {
            addCriterion("updDate is not null");
            return (Criteria) this;
        }

        public Criteria andUpddateEqualTo(Date value) {
            addCriterion("updDate =", value, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateNotEqualTo(Date value) {
            addCriterion("updDate <>", value, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateGreaterThan(Date value) {
            addCriterion("updDate >", value, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateGreaterThanOrEqualTo(Date value) {
            addCriterion("updDate >=", value, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateLessThan(Date value) {
            addCriterion("updDate <", value, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateLessThanOrEqualTo(Date value) {
            addCriterion("updDate <=", value, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateIn(List<Date> values) {
            addCriterion("updDate in", values, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateNotIn(List<Date> values) {
            addCriterion("updDate not in", values, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateBetween(Date value1, Date value2) {
            addCriterion("updDate between", value1, value2, "upddate");
            return (Criteria) this;
        }

        public Criteria andUpddateNotBetween(Date value1, Date value2) {
            addCriterion("updDate not between", value1, value2, "upddate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 08 10:54:33 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}