package com.wx.dev.entity;

import java.util.Date;

public class TblEmployeecsvdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.id
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.code
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.name
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.ptCode
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private String ptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.serviceStatus
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private Integer servicestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.oldCode
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private String oldcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.createDate
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employeecsvdata.updDate
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    private Date upddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.id
     *
     * @return the value of tbl_employeecsvdata.id
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.id
     *
     * @param id the value for tbl_employeecsvdata.id
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.code
     *
     * @return the value of tbl_employeecsvdata.code
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.code
     *
     * @param code the value for tbl_employeecsvdata.code
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.name
     *
     * @return the value of tbl_employeecsvdata.name
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.name
     *
     * @param name the value for tbl_employeecsvdata.name
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.ptCode
     *
     * @return the value of tbl_employeecsvdata.ptCode
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public String getPtcode() {
        return ptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.ptCode
     *
     * @param ptcode the value for tbl_employeecsvdata.ptCode
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setPtcode(String ptcode) {
        this.ptcode = ptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.serviceStatus
     *
     * @return the value of tbl_employeecsvdata.serviceStatus
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public Integer getServicestatus() {
        return servicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.serviceStatus
     *
     * @param servicestatus the value for tbl_employeecsvdata.serviceStatus
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setServicestatus(Integer servicestatus) {
        this.servicestatus = servicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.oldCode
     *
     * @return the value of tbl_employeecsvdata.oldCode
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public String getOldcode() {
        return oldcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.oldCode
     *
     * @param oldcode the value for tbl_employeecsvdata.oldCode
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setOldcode(String oldcode) {
        this.oldcode = oldcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.createDate
     *
     * @return the value of tbl_employeecsvdata.createDate
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.createDate
     *
     * @param createdate the value for tbl_employeecsvdata.createDate
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employeecsvdata.updDate
     *
     * @return the value of tbl_employeecsvdata.updDate
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public Date getUpddate() {
        return upddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employeecsvdata.updDate
     *
     * @param upddate the value for tbl_employeecsvdata.updDate
     *
     * @mbggenerated Wed Mar 08 10:54:33 CST 2017
     */
    public void setUpddate(Date upddate) {
        this.upddate = upddate;
    }
}