package com.wx.dev.entity;

public class TblMulitData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mulit_data.id
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mulit_data.count
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    private String count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mulit_data.createDate
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mulit_data.mark
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mulit_data.id
     *
     * @return the value of tbl_mulit_data.id
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mulit_data.id
     *
     * @param id the value for tbl_mulit_data.id
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mulit_data.count
     *
     * @return the value of tbl_mulit_data.count
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mulit_data.count
     *
     * @param count the value for tbl_mulit_data.count
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public void setCount(String count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mulit_data.createDate
     *
     * @return the value of tbl_mulit_data.createDate
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mulit_data.createDate
     *
     * @param createdate the value for tbl_mulit_data.createDate
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mulit_data.mark
     *
     * @return the value of tbl_mulit_data.mark
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mulit_data.mark
     *
     * @param mark the value for tbl_mulit_data.mark
     *
     * @mbggenerated Tue Dec 13 15:57:28 CST 2016
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}