package com.wx.dev.dao;

import com.wx.dev.entity.TblCustomorganization;
import com.wx.dev.entity.TblCustomorganizationExample;
import com.wx.dev.util.entity.TreeCondition;
import com.wx.dev.util.entity.ZTreeObj;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TblCustomorganizationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int countByExample(TblCustomorganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int deleteByExample(TblCustomorganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int insert(TblCustomorganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int insertSelective(TblCustomorganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	List<TblCustomorganization> selectByExample(
			TblCustomorganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	TblCustomorganization selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TblCustomorganization record,
			@Param("example") TblCustomorganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int updateByExample(@Param("record") TblCustomorganization record,
			@Param("example") TblCustomorganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int updateByPrimaryKeySelective(TblCustomorganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customorganization
	 * @mbggenerated  Fri Dec 02 15:12:44 CST 2016
	 */
	int updateByPrimaryKey(TblCustomorganization record);

	int getMaxOrgId(TblCustomorganization t);

	List<ZTreeObj> getMenu(TreeCondition condition);
}