package com.wx.dev.dao;

import com.wx.dev.entity.TblCustomuser;
import com.wx.dev.entity.TblCustomuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblCustomuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int countByExample(TblCustomuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int deleteByExample(TblCustomuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int insert(TblCustomuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int insertSelective(TblCustomuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	List<TblCustomuser> selectByExample(TblCustomuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	TblCustomuser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TblCustomuser record,
			@Param("example") TblCustomuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int updateByExample(@Param("record") TblCustomuser record,
			@Param("example") TblCustomuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int updateByPrimaryKeySelective(TblCustomuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_customuser
	 * @mbggenerated  Mon Dec 05 16:47:16 CST 2016
	 */
	int updateByPrimaryKey(TblCustomuser record);
}