package com.wx.dev.dao;

import com.wx.dev.entity.TblCorpinfo;
import com.wx.dev.entity.TblCorpinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblCorpinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int countByExample(TblCorpinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int deleteByExample(TblCorpinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int insert(TblCorpinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int insertSelective(TblCorpinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	List<TblCorpinfo> selectByExample(TblCorpinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	TblCorpinfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TblCorpinfo record,
			@Param("example") TblCorpinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int updateByExample(@Param("record") TblCorpinfo record,
			@Param("example") TblCorpinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int updateByPrimaryKeySelective(TblCorpinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_corpinfo
	 * @mbggenerated  Mon Nov 21 16:09:46 CST 2016
	 */
	int updateByPrimaryKey(TblCorpinfo record);
}