package com.wx.dev.dao;

import com.wx.dev.entity.TblDeptcsvdata;
import com.wx.dev.entity.TblDeptcsvdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblDeptcsvdataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int countByExample(TblDeptcsvdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int deleteByExample(TblDeptcsvdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int insert(TblDeptcsvdata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int insertSelective(TblDeptcsvdata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	List<TblDeptcsvdata> selectByExample(TblDeptcsvdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	TblDeptcsvdata selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TblDeptcsvdata record,
			@Param("example") TblDeptcsvdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int updateByExample(@Param("record") TblDeptcsvdata record,
			@Param("example") TblDeptcsvdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int updateByPrimaryKeySelective(TblDeptcsvdata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_deptcsvdata
	 * @mbggenerated  Thu Dec 22 16:38:09 CST 2016
	 */
	int updateByPrimaryKey(TblDeptcsvdata record);
}