package com.wx.dev.dao;

import com.wx.dev.entity.TblEmployeecsvdata;
import com.wx.dev.entity.TblEmployeecsvdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblEmployeecsvdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int countByExample(TblEmployeecsvdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int deleteByExample(TblEmployeecsvdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int insert(TblEmployeecsvdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int insertSelective(TblEmployeecsvdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    List<TblEmployeecsvdata> selectByExample(TblEmployeecsvdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    TblEmployeecsvdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") TblEmployeecsvdata record, @Param("example") TblEmployeecsvdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int updateByExample(@Param("record") TblEmployeecsvdata record, @Param("example") TblEmployeecsvdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int updateByPrimaryKeySelective(TblEmployeecsvdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employeecsvdata
     *
     * @mbggenerated Tue Mar 07 18:39:13 CST 2017
     */
    int updateByPrimaryKey(TblEmployeecsvdata record);
}